# Generated by Django 2.2.7 on 2019-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    operations = [
        migrations.CreateModel(
            name='sf_auth',
            fields=[
                ('SalesforceEdition', models.CharField(max_length=30, null=True)),
                ('SalesforceOrgID', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('OrgName', models.CharField(max_length=20, null=True)),
                ('ConnectedUserName', models.CharField(max_length=20, null=True)),
                ('AccessToken', models.CharField(max_length=120, null=True)),
                ('RefreshToken', models.CharField(max_length=120, null=True)),
                ('SalesforceUserID', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sf_leads',
            fields=[
                ('LeadId', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('Company', models.CharField(max_length=30, null=True)),
                ('OwnerID', models.CharField(max_length=20, null=True)),
                ('LeadSource', models.CharField(max_length=30, null=True)),
                ('CreatedDate', models.DateTimeField(max_length=30, null=True)),
                ('Phone', models.BigIntegerField(null=True)),
                ('City', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
