# Generated by Django 2.2.7 on 2019-11-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFConnect', '0003_sf_leads_auth_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sf_leads',
            name='Phone',
        ),
    ]
