# Generated by Django 2.2.7 on 2019-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFConnect', '0005_auto_20191113_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sf_leads',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
