# Generated by Django 2.2.7 on 2019-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFConnect', '0006_auto_20191113_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='jwt_tokens',
            fields=[
                ('username', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('AccessToken', models.CharField(max_length=120, null=True)),
                ('RefreshToken', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
